# Introduction to tensorflow

This portion of the tutorial, we'll discuss basics of tensorflow in the context of some illustrative numerical examples.

The first step is to import tensorflow:

In [1]:
import tensorflow as tf
import numpy as np

tf.enable_eager_execution()

tf.executing_eagerly()

print('Loaded TensorFlow version ' + tf.__version__)

Loaded TensorFlow version 1.13.1


After version 1.7, TensorFlow supports a new execution mode that is easier for use with the interactive python interpreter. Google describes its eager execution mode as "an imperative programming environment that evaluates operations immediately, without building graphs: operations return concrete values instead of constructing a computational graph to run later."

TensorFlow used to only support creating a graph first and only evaluating operations in the context of "sessions."

Let's try making a tensor. First, we'll create a numpy array. Then we'll convert the numpy array into a TF tensor.

In [3]:
x_data = np.array([[[ 1.,  2.,  3.], [ 4.,  5.,  6.]],
                   [[ 7.,  8.,  9.], [10., 11., 12.]],
                   [[13., 14., 15.], [16., 17., 99.]]])

print(x_data)

print('\n x has shape: \n')

print(np.shape(x_data))

# now let's make a TF tensor from the data
x = tf.convert_to_tensor(x_data, dtype = tf.float32)

print('\n x is now a \n')

print(x)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]

 [[13. 14. 15.]
  [16. 17. 99.]]]

 x has shape: 

(3, 2, 3)

 x is now a 

tf.Tensor(
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]

 [[13. 14. 15.]
  [16. 17. 99.]]], shape=(3, 2, 3), dtype=float32)


Slicing is a common operation performed on tensors. Let's try looking at a few slices of x

In [40]:
print('Slicing is performed from a start index to a finishing index.')
print('If I slice from (0,0,0) to (3,2,3), I obtain the entire tensor: \n')
print(tf.slice(x,[0,0,0],[3,2,3])) # the whole tensor

print('\n If I slice from (1,0,0) to (2,2,3), I obtain: \n')
print(tf.slice(x,[1,0,0],[2,2,3]))

print('\n If I slice from (2,0,0) to (3,2,3), I obtain: \n')
print(tf.slice(x,[2,0,0],[1,2,3]))

print('\n If I slice from (0,1,0) to (3,2,3), I obtain: \n')
print(tf.slice(x,[0,1,0],[3,1,3]))
print(tf.slice(x,[0,0,1],[3,2,1]))
print(tf.slice(x,[0,0,1],[3,2,2]))

Slicing is performed from a start index to a finishing index.
If I slice from (0,0,0) to (3,2,3), I obtain the entire tensor: 

tf.Tensor(
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]

 [[13. 14. 15.]
  [16. 17. 18.]]], shape=(3, 2, 3), dtype=float32)

 If I slice from (1,0,0) to (2,2,3), I obtain: 

tf.Tensor(
[[[ 7.  8.  9.]
  [10. 11. 12.]]

 [[13. 14. 15.]
  [16. 17. 18.]]], shape=(2, 2, 3), dtype=float32)

 If I slice from (2,0,0) to (3,2,3), I obtain: 

tf.Tensor(
[[[13. 14. 15.]
  [16. 17. 18.]]], shape=(1, 2, 3), dtype=float32)

 If I slice from (0,1,0) to (3,2,3), I obtain: 

tf.Tensor(
[[[ 4.  5.  6.]]

 [[10. 11. 12.]]

 [[16. 17. 18.]]], shape=(3, 1, 3), dtype=float32)
tf.Tensor(
[[[ 2.]
  [ 5.]]

 [[ 8.]
  [11.]]

 [[14.]
  [17.]]], shape=(3, 2, 1), dtype=float32)
tf.Tensor(
[[[ 2.  3.]
  [ 5.  6.]]

 [[ 8.  9.]
  [11. 12.]]

 [[14. 15.]
  [17. 18.]]], shape=(3, 2, 2), dtype=float32)
